language: php
sudo: false
dist: trusty
services:
  - postgresql
matrix:
  include:
    - php: 7.2
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
    - php: 7.3
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^8.0
  fast_finish: true
  allow_failures:
    - php: 7.3
before_script:
  - curl --version
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - travis_retry composer install --no-interaction --prefer-source --dev
  - cp phpunit.xml.travis phpunit.xml
  - cp .env.travis .env
  - psql -c 'create database travis_test;' -U postgres
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" || "$TRAVIS_PHP_VERSION" != "7.1" ]]; then
    echo "xdebug.overload_var_dump = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    || true; fi
  - php artisan migrate
script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then vendor/bin/phpunit --verbose --coverage-text
    --coverage-clover build/logs/clover.xml; fi

before_install:

- openssl aes-256-cbc -K $encrypted_97e22d8076f3_key -iv $encrypted_97e22d8076f3_iv -in deploy_prod.enc -out deploy_key -d
- if [ "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" ]; then eval "$(ssh-agent -s)"; fi
- if [ "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" ]; then chmod 600 ./deploy_key; fi
- if [ "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" ]; then echo -e "Host 68.183.176.96\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config; fi
- if [ "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" ]; then ssh-add ./deploy_key; fi

after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" == "develop" ]; then ssh -i ./deploy_key travis@68.183.176.96 -p 22 "cd /var/www/html/library && git pull origin develop"; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then ssh -i ./deploy_key travis-prod@128.199.134.135 -p 22 "cd /var/www/html/perpus-prod && git pull origin master"; fi
